### ISSUE TITLE
Bezorgopties worden niet getoond na keuze voor Afhalen en weer terug kiezen voor Bezorgen

### ISSUE THREAD

**Issue by RobertVerdonschot** [myparcelbe/woocommerce#123]
Standaard is de optie Bezorgen actief. Dan worden de MyParcel bezorgopties getoond.
Als ik dan voor Afhalen kies, worden de bezorgopties niet getoond. Dat is OK.

Als ik dan weer kies voor Bezorgen, worden de bezorgopties van MyParcel niet meer getoond.

Dit probleem heet de Nederlandse MyParcel plugin niet.
Mogelijk is dit dus gefixed nadat de Belgische plugin is geforked, ik denk in versie 3.1.6.

**Comment by RichardPerdaan** [comment]
Beste @RobertVerdonschot   ,
Dank je wel voor het melden van dit probleem. 
Vandaag is versie 4.3.2 live gezet. 
Met deze versie is dit probleem opgelost.
