### ISSUE TITLE
Als verzendopties niet zijn ingeschakeld > wordt geen vervoerder aangewezen

### ISSUE THREAD

**Issue by soedesh** [myparcelbe/woocommerce#130]
Plugin versie: 
4.1.3

Extra toelichting:

Het lijkt er op dat wanneer de verzendopties er niet bij staan, er ook geen vervoerder wordt gekozen. Hierdoor komt er onder de tab “bestemming” in het orderoverzicht, bij vervoerder altijd DPD te staan. Als je dan wil exporteren, lukt het niet of komt er een Bpost label uit. (ook al staat bpost vaak niet geactiveerd)

Dit in combinatie met het issue waarbij de verzendopties verdwijnen bij het veranderen van de verzendmethode (afhalen in winkel) zorgt er voor dat er heel veel orders niet geëxporteerd kunnen worden. 

Case: 828315

**Comment by RichardPerdaan** [comment]
Hi @soedesh   ,
Dank je wel voor het melden van dit probleem. 
Vandaag is versie 4.3.2 live gezet. 
Met deze versie is dit probleem opgelost.
