### ISSUE TITLE
Alleen afhalen bij dpd locatie mogelijk in checkout 

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelbe/woocommerce#138]
Wanneer alle bezorgopties getoond zouden moeten worden, worden er voor onder andere frankrijk en duitsland alleen maar dpd pickup locaties getoond en geen levering aan huis. 

<img width="544" alt="Afrekenen – Test- België 2020-09-25 14-15-15" src="https://user-images.githubusercontent.com/54140706/94265974-b601a000-ff39-11ea-9584-2cb7e50eae70.png">

**Comment by Nikitaverh** [comment]
00856331

**Comment by EdieLemoine** [comment]
@Nikitaverh kun je de gebruikte myparcelconfig delen?

**Comment by Nikitaverh** [comment]
@EdieLemoine Ik heb alle bezorgopties van alle vervoerders aangezet, (afhaal en thuisbezorgd) Heb je toegang tot de BE testomgeving? Als het goed is, staat deze nog op die manier ingesteld

**Comment by RichardPerdaan** [comment]
Hi @NikitaMyParcel   ,
Dank je wel voor het melden van dit probleem. 
Vandaag is versie 4.3.2 live gezet. 
Met deze versie is dit probleem opgelost.
