### ISSUE TITLE
As a client I want the correct link to be showed in my order overview and send the right one to my client

### ISSUE THREAD

**Issue by TimBlom** [myparcelbe/woocommerce#150]
When I create a PostNL label the tracking link in my order overview is connected to bpost. The customer also receives the wrong link.

**Comment by TimBlom** [comment]
Case 00994333

**Comment by blaatpraat** [comment]
#161 I can see that this is the same as the issue (including workaround) that I've just created.

**Comment by RichardPerdaan** [comment]
Hi @TimBlom ,
Thank you for reporting this issue.
Today version 4.3.2 has been released.
This version solves this problem.
