### ISSUE TITLE
Vervoerders uitgeschakeld maar toch zichtbaar bij bezorgopties

### ISSUE THREAD

**Issue by TeunSmit** [myparcelbe/woocommerce#157]
Plugin versie: 4.1.7
Welke stappen moet je volgen om het probleem te kunnen reproduceren:
MyParcel settings -> Bpost enabled -> DPD en PNL disabled -> Bezorgopties > enables
Ga nu naar de checkout en je ziet alle vervoerders staan.
<img width="967" alt="Schermafbeelding 2021-03-22 om 11 08 23" src="https://user-images.githubusercontent.com/54140671/112167955-2e979f80-8bf1-11eb-8f69-80e399329699.png">

**Comment by RichardPerdaan** [comment]
Beste @TeunSmit  ,
Dank je wel voor het melden van dit probleem. 
Vandaag is versie 4.3.2 live gezet. 
Met deze versie is dit probleem opgelost.
