### ISSUE TITLE
Adres pickup punt niet op succespagina en orderbevestiging. 

### ISSUE THREAD

**Issue by yannickdaems** [myparcelbe/woocommerce#159]
Als klanten voor een levering aan afhaalpunt kiezen, is er op de succespagina enkel het opgegeven facturatieadres te zien. Ook in de orderbevestiging staat er het adres van de klant in de plaats van dat van het afhaalpunt. 

<img width="533" alt="Schermafbeelding 2021-04-26 om 14 02 01" src="https://user-images.githubusercontent.com/71638234/116079371-0390e780-a698-11eb-94bf-be99e800e4b9.png">
<img width="823" alt="Schermafbeelding 2021-04-26 om 13 55 46" src="https://user-images.githubusercontent.com/71638234/116079392-0ab7f580-a698-11eb-85f4-b1d57a6b3e93.png">

De labels worden wel effectief aangemaakt voor het afhaalpunt, maar dit schept verwarring bij eindklanten.

**Comment by RichardPerdaan** [comment]
Beste @yannickdaems ,
Dank je wel voor het melden van dit probleem. Vandaag is versie 4.3.2 live gezet. 
Met deze versie is dit probleem opgelost.
