### ISSUE TITLE
Bestellingen verdwijnen na activering plugin

### ISSUE THREAD

**Issue by MUDEBE** [myparcelbe/woocommerce#167]
Na activering van de MyparcelBE module verdwijnt het bestellingen overzicht in Woocommerce. Vanuit Wordpress ontstaat er deze foutmelding: 
_Een fout van het type E_ERROR werd veroorzaakt op regelnummer 32 van het bestand /home/wordpress/live/wp-content/plugins/wc-myparcel-belgium/includes/admin/class-wcmpbe-country-codes.php. Foutmelding: Uncaught Error: Call to undefined method WC_Countries::country_exists() in /home/wordpress/live/wp-content/plugins/wc-myparcel-belgium/includes/admin/class-wcmpbe-country-codes.php:32
Stack trace:
#0 /home/wordpress/live/wp-content/plugins/wc-myparcel-belgium/includes/admin/class-wcmpbe-country-codes.php(47): WCMPBE_Country_Codes::isWorldShipmentCountry()
#1 /home/wordpress/live/wp-content/plugins/wc-myparcel-belgium/includes/admin/class-wcmypabe-admin.php(453): WCMPBE_Country_Codes::isAllowedDestination()
#2 /home/wordpress/live/wp-includes/class-wp-hook.php(287): WCMYPABE_Admin->showOrderActions()
#3 /home/wordpress/live/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#4 /home/wordpress/live/wp-includes/plugin.php(484): WP_Hook->do_action()
#5 /home/wordpress/live/wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-orders.php(311): do_action()
#6 /home/wordpress/live/wp-content/plugins/woocommerce/includes/admin/list-tables/abstract-class-wc-admin-list-table.php(_

Verdere info:
WordPress versie 5.6.4
Huidige plugin: WC MyParcel Belgium (versie 4.3.5)
PHP versie 7.4.18

**Comment by RichardPerdaan** [comment]
Beste @MUDEBE ,
Doordat wij een nieuwe functionaliteit hebben toegevoegd adviseren wij een minimale versie van 5.1.0 van de WooCommerce release. Mijn advies is dan ook om deze te updaten naar minimaal 5.1.0. Ik verwacht dat de problemen dan opgelost zijn.
