### ISSUE TITLE
Version 4.4.1 crashed my website

### ISSUE THREAD

**Issue by 2990kenny** [myparcelbe/woocommerce#171]
**Describe the bug**
Version 4.4.1 crashed my website. Reverse to 4.4.0 and everything works fine.

**Details**
 - WordPress version: 5.8.1
 - WooCommerce version: 5.6.0
 - WooCommerce MyParcel version: 4.4.1
 - Theme: DIVI (also tested with other theme, same problem)

**Additional context**
Error Details
=============
An error of type E_ERROR was caused in line 25 of the file /customers/c/4/0/discocake.be/httpd.www/wp-content/plugins/wc-myparcel-belgium/vendor/composer/autoload_real.php. Error message: Uncaught Error: Failed opening required '/customers/c/4/0/discocake.be/httpd.www/wp-content/plugins/wc-myparcel-belgium/vendor/composer/platform_check.php' (include_path='.:/usr/share/php') in /customers/c/4/0/discocake.be/httpd.www/wp-content/plugins/wc-myparcel-belgium/vendor/composer/autoload_real.php:25
Stack trace:
#0 /customers/c/4/0/discocake.be/httpd.www/wp-content/plugins/wc-myparcel-belgium/vendor/autoload.php(7): ComposerAutoloaderInit5478826536c5ca2c9766c12ac98ddd31::getLoader()
#1 /customers/c/4/0/discocake.be/httpd.www/wp-content/plugins/wc-myparcel-belgium/woocommerce-myparcel.php(131): require_once('/customers/c/4/...')
#2 /customers/c/4/0/discocake.be/httpd.www/wp-content/plugins/wc-myparcel-belgium/woocommerce-myparcel.php(185): WCMYPABE->includes()
#3 /customers/c/4/0/discocake.be/httpd.www/wp-includes/class-wp-hook.php(303): WCMYPABE->load_classes('')
#4 /customers/c/4/0/discocake.be/httpd.www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#5 /customers/c/4/0/discocake.be/httpd.www/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /customers/c/4/0/discocake.be/httpd.www/wp-settings.php(578): do_action('init')
#7 /customers/c/4/0/discocake.be/httpd.www/wp-config.php(94): require_once('/customers/c/4/...')
#8 /customers/c/4/0/discocake.be/httpd.www/wp-load.php(50): require_once('/customers/c/4/...')
#9 /customers/c/4/0/discocake.be/httpd.www/wp-admin/admin.php(34): require_once('/customers/c/4/...')
#10 /customers/c/4/0/discocake.be/httpd.www/wp-admin/index.php(10): require_once('/customers/c/4/...')
#11 {main}
  thrown

**Comment by Noewt** [comment]
the file '/wp-content/plugins/wc-myparcel-belgium/vendor/composer/platform_check.php' is missing

**Comment by joerivanveen** [comment]
This was an omission indeed. It is now fixed. Thank you for bringing this to our attention.
