### ISSUE TITLE
Delivery date shown in order confirmation when "Delivery days window" is set to off in checkout

### ISSUE THREAD

**Issue by Chris707** [myparcelbe/woocommerce#60]
Delivery date shown in the order confirmation when "Delivery days window" is set to off in checkout.
Wanneer "Delivery days window" is uitgeschakeld dan zou de  "Delivery date" niet getoond moeten worden in de orderbevestiging maar helaas is dit wel het geval.

**Comment by adem-demir** [comment]
Er komt vanaf 4.0.6 een optie om dit te kunnen inschakelen/uitschakelen
