### ISSUE TITLE
The checkout does not refresh after switching shipping methods

### ISSUE THREAD

**Issue by TimBlom** [myparcelbe/woocommerce#69]
step 1: Select a delivery option.
step 2: Select another shipping method > This results in the disappearance of the checkout (and the costs)
step 3: Select the first shipping method again

result: The checkout options are selected, but the costs are not charged.

https://monosnap.com/file/PW0zOt9NzECdjKlmoME9Ulw34gwfhn

**Comment by RichardPerdaan** [comment]
solved in version [v4.0.0](https://github.com/myparcelbe/woocommerce/releases/tag/v4.0.0)
